name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install"
        run: python3 -m pip install -r requirements.txt
      - name: "Linter"
        run: pylint app